mysql:
  image: mysql:5.6
  container_name: mysql
  environment:
    - MYSQL_ROOT_PASSWORD=123456
    - MYSQL_DATABASE=test
web:
  image: springboot-test:latest
  container_name: springboot-test
  links:
    - mysql
